import type { TrainOption, TravelPackage } from './types';

export const CITIES: Record<string, string> = {
  DEL: 'New Delhi',
  MUM: 'Mumbai',
  BLR: 'Bangalore',
  CHE: 'Chennai',
  KOL: 'Kolkata',
  HYD: 'Hyderabad',
  AGA: 'Agra',
  JAI: 'Jaipur',
  GOA: 'Goa',
  PUN: 'Pune',
  LKO: 'Lucknow',
  AMD: 'Ahmedabad',
};

export const mockTrains: TrainOption[] = [
  { id: 't1', trainName: 'Rajdhani Express', trainNumber: '12951', departureStation: 'New Delhi', arrivalStation: 'Mumbai Central', departureTime: '16:55', arrivalTime: '08:15', duration: '15h 20m', class: 'AC First Class', availableSeats: 24, price: 4215, daysOfOperation: 'Daily' },
  { id: 't2', trainName: 'Shatabdi Express', trainNumber: '12002', departureStation: 'New Delhi', arrivalStation: 'Bhopal', departureTime: '06:15', arrivalTime: '14:25', duration: '8h 10m', class: 'AC Chair Car', availableSeats: 78, price: 1180, daysOfOperation: 'Except Sun' },
  { id: 't3', trainName: 'Duronto Express', trainNumber: '12213', departureStation: 'Mumbai Central', arrivalStation: 'New Delhi', departureTime: '23:05', arrivalTime: '16:15', duration: '17h 10m', class: 'AC 3-Tier', availableSeats: 192, price: 1650, daysOfOperation: 'Mon, Thu, Sat' },
  { id: 't4', trainName: 'Karnataka Express', trainNumber: '12627', departureStation: 'New Delhi', arrivalStation: 'Bangalore', departureTime: '21:20', arrivalTime: '06:40', duration: '33h 20m', class: 'AC 2-Tier', availableSeats: 54, price: 2890, daysOfOperation: 'Daily' },
  { id: 't5', trainName: 'Tamil Nadu Express', trainNumber: '12621', departureStation: 'New Delhi', arrivalStation: 'Chennai Central', departureTime: '22:30', arrivalTime: '07:10', duration: '32h 40m', class: 'AC 2-Tier', availableSeats: 48, price: 2750, daysOfOperation: 'Daily' },
  { id: 't6', trainName: 'Howrah Rajdhani', trainNumber: '12301', departureStation: 'New Delhi', arrivalStation: 'Howrah', departureTime: '16:50', arrivalTime: '09:55', duration: '17h 05m', class: 'AC First Class', availableSeats: 18, price: 3890, daysOfOperation: 'Daily' },
  { id: 't7', trainName: 'Gatimaan Express', trainNumber: '12050', departureStation: 'New Delhi', arrivalStation: 'Agra Cantt', departureTime: '08:10', arrivalTime: '09:50', duration: '1h 40m', class: 'AC Chair Car', availableSeats: 120, price: 990, daysOfOperation: 'Except Fri' },
  { id: 't8', trainName: 'Deccan Queen', trainNumber: '12123', departureStation: 'Mumbai CST', arrivalStation: 'Pune', departureTime: '07:15', arrivalTime: '10:25', duration: '3h 10m', class: 'AC Chair Car', availableSeats: 96, price: 580, daysOfOperation: 'Daily' },
  { id: 't9', trainName: 'Vande Bharat Express', trainNumber: '22436', departureStation: 'New Delhi', arrivalStation: 'Varanasi', departureTime: '06:00', arrivalTime: '14:00', duration: '8h 00m', class: 'AC Chair Car', availableSeats: 104, price: 1695, daysOfOperation: 'Mon-Sat' },
  { id: 't10', trainName: 'Tejas Express', trainNumber: '22120', departureStation: 'Mumbai CST', arrivalStation: 'Goa', departureTime: '05:50', arrivalTime: '14:35', duration: '8h 45m', class: 'AC Chair Car', availableSeats: 88, price: 1280, daysOfOperation: 'Except Mon' },
  { id: 't11', trainName: 'Mysore Shatabdi', trainNumber: '12007', departureStation: 'Bangalore', arrivalStation: 'Mysore', departureTime: '11:00', arrivalTime: '13:10', duration: '2h 10m', class: 'AC Chair Car', availableSeats: 150, price: 455, daysOfOperation: 'Daily' },
  { id: 't12', trainName: 'Jaipur Superfast', trainNumber: '12015', departureStation: 'New Delhi', arrivalStation: 'Jaipur', departureTime: '17:40', arrivalTime: '22:30', duration: '4h 50m', class: 'AC 3-Tier', availableSeats: 64, price: 785, daysOfOperation: 'Daily' },
  { id: 't13', trainName: 'AP Express', trainNumber: '12723', departureStation: 'New Delhi', arrivalStation: 'Hyderabad', departureTime: '06:25', arrivalTime: '05:15', duration: '22h 50m', class: 'AC 2-Tier', availableSeats: 36, price: 2450, daysOfOperation: 'Daily' },
  { id: 't14', trainName: 'Lucknow Mail', trainNumber: '12229', departureStation: 'New Delhi', arrivalStation: 'Lucknow', departureTime: '22:20', arrivalTime: '05:20', duration: '7h 00m', class: 'AC 3-Tier', availableSeats: 72, price: 950, daysOfOperation: 'Daily' },
  { id: 't15', trainName: 'Ahmedabad Shatabdi', trainNumber: '12010', departureStation: 'Mumbai Central', arrivalStation: 'Ahmedabad', departureTime: '06:25', arrivalTime: '13:00', duration: '6h 35m', class: 'AC Chair Car', availableSeats: 92, price: 870, daysOfOperation: 'Except Sun' },
];

export const mockPackages: TravelPackage[] = [
  {
    id: 'p1', name: 'Royal Rajasthan Explorer', destination: 'Rajasthan', category: 'domestic',
    duration: '7 Days / 6 Nights', durationDays: 7, price: 28999, originalPrice: 35999,
    description: 'Explore the royal heritage of Rajasthan visiting magnificent forts, palaces, and vibrant bazaars across Jaipur, Udaipur, and Jodhpur.',
    highlights: ['Visit Amber Fort & Hawa Mahal', 'Boat ride on Lake Pichola', 'Mehrangarh Fort tour', 'Camel safari in Thar Desert', 'Traditional Rajasthani dinner'],
    inclusions: ['6 Nights Hotel Stay', 'Daily Breakfast & Dinner', 'AC Transport', 'All Sightseeing', 'Expert Guide', 'Monument Entry Fees'],
    exclusions: ['Flights', 'Lunch', 'Personal Expenses', 'Travel Insurance'],
    itinerary: [
      { day: 1, title: 'Arrival in Jaipur', description: 'Arrive at Jaipur airport. Transfer to hotel. Evening visit to Birla Mandir and local market.' },
      { day: 2, title: 'Jaipur Sightseeing', description: 'Visit Amber Fort, Hawa Mahal, City Palace, and Jantar Mantar. Evening at Chokhi Dhani.' },
      { day: 3, title: 'Jaipur to Jodhpur', description: 'Drive to Jodhpur via Ajmer. Visit Pushkar Lake en route. Evening at leisure.' },
      { day: 4, title: 'Jodhpur Exploration', description: 'Visit Mehrangarh Fort, Jaswant Thada, and Umaid Bhawan Palace. Evening walking tour.' },
      { day: 5, title: 'Jodhpur to Udaipur', description: 'Scenic drive to Udaipur via Ranakpur Jain Temples. Arrive and relax.' },
      { day: 6, title: 'Udaipur City Tour', description: 'Visit City Palace, boat ride on Lake Pichola, Saheliyon ki Bari. Farewell dinner.' },
      { day: 7, title: 'Departure', description: 'Transfer to airport for departure. Tour ends with beautiful memories.' },
    ],
    image: 'https://images.unsplash.com/photo-1477587458883-47145ed94245?w=800', rating: 4.8, reviews: 342, maxGroupSize: 20,
  },
  {
    id: 'p2', name: 'Kerala Backwater Bliss', destination: 'Kerala', category: 'domestic',
    duration: '6 Days / 5 Nights', durationDays: 6, price: 24999, originalPrice: 31999,
    description: 'Experience God\'s Own Country with serene backwaters, lush tea gardens, and pristine beaches across Kochi, Munnar, and Alleppey.',
    highlights: ['Houseboat cruise in Alleppey', 'Tea garden visit in Munnar', 'Kathakali dance show', 'Spice plantation tour', 'Beach sunset at Kovalam'],
    inclusions: ['5 Nights Stay (Hotels + Houseboat)', 'All Meals on Houseboat', 'Breakfast at Hotels', 'AC Transport', 'Sightseeing'],
    exclusions: ['Flights', 'Lunch & Dinner at Hotels', 'Personal Expenses'],
    itinerary: [
      { day: 1, title: 'Arrival in Kochi', description: 'Visit Fort Kochi, Chinese Fishing Nets, St. Francis Church. Evening Kathakali show.' },
      { day: 2, title: 'Kochi to Munnar', description: 'Scenic drive through spice plantations. Visit Cheeyappara Waterfalls. Arrive Munnar.' },
      { day: 3, title: 'Munnar Sightseeing', description: 'Visit Tea Museum, Eravikulam National Park, Mattupetty Dam, and Echo Point.' },
      { day: 4, title: 'Munnar to Alleppey', description: 'Drive to Alleppey. Board traditional houseboat. Cruise through backwaters.' },
      { day: 5, title: 'Alleppey to Kovalam', description: 'Disembark houseboat. Drive to Kovalam Beach. Evening beach activities.' },
      { day: 6, title: 'Departure', description: 'Morning at leisure. Transfer to Trivandrum airport for departure.' },
    ],
    image: 'https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=800', rating: 4.7, reviews: 289, maxGroupSize: 15,
  },
  {
    id: 'p3', name: 'Goa Beach Holiday', destination: 'Goa', category: 'domestic',
    duration: '5 Days / 4 Nights', durationDays: 5, price: 16999, originalPrice: 22999,
    description: 'Sun, sand, and adventure in India\'s beach paradise. Explore North and South Goa beaches, heritage sites, and nightlife.',
    highlights: ['North Goa beach hopping', 'Old Goa churches visit', 'Dudhsagar Falls excursion', 'Water sports activities', 'Cruise on Mandovi River'],
    inclusions: ['4 Nights Beach Resort', 'Daily Breakfast', 'AC Transport', 'Sightseeing', 'Water Sports Package'],
    exclusions: ['Flights', 'Lunch & Dinner', 'Nightlife Expenses'],
    itinerary: [
      { day: 1, title: 'Arrival in Goa', description: 'Airport transfer. Check into beach resort. Evening Mandovi River cruise.' },
      { day: 2, title: 'North Goa Tour', description: 'Visit Calangute, Baga, Anjuna beaches. Fort Aguada and Chapora Fort.' },
      { day: 3, title: 'Heritage & Adventure', description: 'Old Goa churches, Se Cathedral. Afternoon water sports at Baga Beach.' },
      { day: 4, title: 'South Goa & Dudhsagar', description: 'Excursion to Dudhsagar Falls. Visit Palolem Beach. Spice plantation tour.' },
      { day: 5, title: 'Departure', description: 'Morning at leisure on beach. Transfer to airport.' },
    ],
    image: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=800', rating: 4.5, reviews: 456, maxGroupSize: 25,
  },
  {
    id: 'p4', name: 'Kashmir Paradise', destination: 'Kashmir', category: 'domestic',
    duration: '6 Days / 5 Nights', durationDays: 6, price: 32999, originalPrice: 42999,
    description: 'Discover the paradise on earth with snow-capped mountains, pristine lakes, and Mughal gardens in Srinagar, Gulmarg, and Pahalgam.',
    highlights: ['Shikara ride on Dal Lake', 'Gondola ride in Gulmarg', 'Stay in luxury houseboat', 'Visit Mughal Gardens', 'Pahalgam valley trek'],
    inclusions: ['5 Nights Stay (Hotels + Houseboat)', 'Daily Breakfast & Dinner', 'AC Transport', 'Gondola Tickets', 'All Sightseeing'],
    exclusions: ['Flights', 'Lunch', 'Personal Shopping', 'Pony Rides'],
    itinerary: [
      { day: 1, title: 'Arrival in Srinagar', description: 'Airport pickup. Check into luxury houseboat on Dal Lake. Evening Shikara ride.' },
      { day: 2, title: 'Mughal Gardens', description: 'Visit Nishat Bagh, Shalimar Bagh, and Chashme Shahi. Afternoon at Shankaracharya Temple.' },
      { day: 3, title: 'Srinagar to Gulmarg', description: 'Drive to Gulmarg. Gondola ride to Apharwat Peak. Snow activities. Return to Srinagar.' },
      { day: 4, title: 'Srinagar to Pahalgam', description: 'Drive to Pahalgam via Pampore Saffron fields. Visit Aru Valley and Betaab Valley.' },
      { day: 5, title: 'Pahalgam Exploration', description: 'Visit Chandanwari, Baisaran meadows. Pony ride. Return to Srinagar.' },
      { day: 6, title: 'Departure', description: 'Morning shopping at local markets. Transfer to Srinagar airport.' },
    ],
    image: 'https://images.unsplash.com/photo-1587474260584-136574528ed5?w=800', rating: 4.9, reviews: 198, maxGroupSize: 12,
  },
  {
    id: 'p5', name: 'Himachal Hill Escape', destination: 'Himachal Pradesh', category: 'domestic',
    duration: '7 Days / 6 Nights', durationDays: 7, price: 22999, originalPrice: 29999,
    description: 'Mountain escape through Shimla, Manali, and Dharamsala with scenic valleys, adventure activities, and peaceful monasteries.',
    highlights: ['Rohtang Pass excursion', 'Solang Valley adventure', 'Mall Road Shimla walk', 'Dalai Lama Temple visit', 'River rafting in Kullu'],
    inclusions: ['6 Nights Hotel', 'Daily Breakfast', 'Volvo Bus from Delhi', 'AC Transport', 'All Sightseeing'],
    exclusions: ['Lunch & Dinner', 'Adventure Activity Fees', 'Personal Expenses'],
    itinerary: [
      { day: 1, title: 'Delhi to Shimla', description: 'Overnight Volvo from Delhi. Arrive Shimla morning. Rest and evening Mall Road walk.' },
      { day: 2, title: 'Shimla Sightseeing', description: 'Visit Kufri, Jakhoo Temple, Christ Church, and Scandal Point. Toy train ride.' },
      { day: 3, title: 'Shimla to Manali', description: 'Scenic drive to Manali via Kullu valley. River rafting en route. Arrive evening.' },
      { day: 4, title: 'Manali Local Tour', description: 'Visit Hadimba Temple, Vashisht Hot Springs, Old Manali, and Manu Temple.' },
      { day: 5, title: 'Solang & Rohtang', description: 'Excursion to Solang Valley for adventure sports. Visit Rohtang Pass (subject to weather).' },
      { day: 6, title: 'Manali to Dharamsala', description: 'Drive to Dharamsala. Visit Dalai Lama Temple, Bhagsunath Falls, and Mcleodganj.' },
      { day: 7, title: 'Departure', description: 'Morning tea at Dharamsala. Departure transfer to Pathankot/Dharamsala airport.' },
    ],
    image: 'https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=800', rating: 4.6, reviews: 267, maxGroupSize: 18,
  },
  {
    id: 'p6', name: 'Dubai Luxury Getaway', destination: 'Dubai', category: 'international',
    duration: '5 Days / 4 Nights', durationDays: 5, price: 52999, originalPrice: 68999,
    description: 'Experience the glamour of Dubai with iconic landmarks, desert adventure, luxury shopping, and world-class entertainment.',
    highlights: ['Burj Khalifa At The Top', 'Desert Safari with BBQ dinner', 'Dubai Mall & Fountain Show', 'Dhow Cruise dinner', 'Palm Jumeirah tour'],
    inclusions: ['4 Nights 4-Star Hotel', 'Daily Breakfast', 'Airport Transfers', 'Desert Safari', 'Dhow Cruise Dinner', 'City Tour'],
    exclusions: ['Flights', 'Visa Fees', 'Lunch', 'Shopping Expenses'],
    itinerary: [
      { day: 1, title: 'Arrival in Dubai', description: 'Airport transfer. Check into hotel. Evening Dubai Marina walk and dinner.' },
      { day: 2, title: 'Dubai City Tour', description: 'Visit Burj Khalifa, Dubai Mall, Dubai Frame, and Gold Souk. Evening Fountain Show.' },
      { day: 3, title: 'Desert Safari', description: 'Morning at leisure. Afternoon desert safari with dune bashing, camel ride, and BBQ dinner.' },
      { day: 4, title: 'Palm & Marina', description: 'Visit Palm Jumeirah, Atlantis the Palm. Afternoon at JBR Beach. Evening Dhow Cruise dinner.' },
      { day: 5, title: 'Departure', description: 'Morning shopping at outlet mall. Airport transfer for departure.' },
    ],
    image: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=800', rating: 4.7, reviews: 523, maxGroupSize: 20,
  },
  {
    id: 'p7', name: 'Thailand Discovery', destination: 'Thailand', category: 'international',
    duration: '6 Days / 5 Nights', durationDays: 6, price: 39999, originalPrice: 49999,
    description: 'Discover the Land of Smiles with Bangkok\'s temples, Pattaya\'s beaches, and floating markets in this incredible Thai adventure.',
    highlights: ['Grand Palace & Wat Pho', 'Floating Market visit', 'Coral Island day trip', 'Alcazar Show Pattaya', 'Thai cooking class'],
    inclusions: ['5 Nights Hotel', 'Daily Breakfast', 'Airport Transfers', 'Coral Island Tour', 'City Tours', 'All Entry Tickets'],
    exclusions: ['Flights', 'Visa on Arrival', 'Lunch & Dinner', 'Personal Expenses'],
    itinerary: [
      { day: 1, title: 'Arrival in Bangkok', description: 'Airport transfer. Evening Chao Phraya River cruise with dinner.' },
      { day: 2, title: 'Bangkok Temple Tour', description: 'Visit Grand Palace, Wat Pho, Wat Arun. Afternoon at Chatuchak Market.' },
      { day: 3, title: 'Floating Market', description: 'Visit Damnoen Saduak Floating Market. Afternoon Thai cooking class.' },
      { day: 4, title: 'Bangkok to Pattaya', description: 'Transfer to Pattaya. Visit Nong Nooch Garden. Evening Alcazar Show.' },
      { day: 5, title: 'Coral Island', description: 'Full day at Coral Island with water sports. Evening Walking Street.' },
      { day: 6, title: 'Departure', description: 'Transfer to Bangkok airport for departure flight.' },
    ],
    image: 'https://images.unsplash.com/photo-1528181304800-259b08848526?w=800', rating: 4.6, reviews: 412, maxGroupSize: 25,
  },
  {
    id: 'p8', name: 'Bali Tropical Paradise', destination: 'Bali', category: 'international',
    duration: '7 Days / 6 Nights', durationDays: 7, price: 45999, originalPrice: 59999,
    description: 'Escape to Bali\'s tropical paradise with stunning temples, rice terraces, beaches, and world-class wellness experiences.',
    highlights: ['Ubud Rice Terraces', 'Tanah Lot sunset', 'Kintamani volcano view', 'Waterbom Bali', 'Traditional spa treatment'],
    inclusions: ['6 Nights Pool Villa/Hotel', 'Daily Breakfast', 'Airport Transfers', 'All Tours & Entry Fees', 'Spa Session', 'Water Sports'],
    exclusions: ['Flights', 'Visa', 'Lunch & Dinner', 'Personal Shopping'],
    itinerary: [
      { day: 1, title: 'Arrival in Bali', description: 'Airport transfer to Seminyak. Evening beach walk and welcome dinner.' },
      { day: 2, title: 'South Bali Tour', description: 'Visit Uluwatu Temple, Padang Padang Beach. Evening Kecak dance at sunset.' },
      { day: 3, title: 'Ubud Exploration', description: 'Transfer to Ubud. Visit Monkey Forest, Tegalalang Rice Terraces, and art galleries.' },
      { day: 4, title: 'Kintamani & Temples', description: 'Visit Mount Batur viewpoint, Tirta Empul Temple, and coffee plantation.' },
      { day: 5, title: 'Water Activities', description: 'Morning Waterbom Bali. Afternoon snorkeling at Nusa Dua. Evening spa treatment.' },
      { day: 6, title: 'Tanah Lot & Shopping', description: 'Visit Tanah Lot Temple at sunset. Shopping at Seminyak boutiques. Farewell dinner.' },
      { day: 7, title: 'Departure', description: 'Morning at leisure. Transfer to airport for departure.' },
    ],
    image: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=800', rating: 4.8, reviews: 378, maxGroupSize: 15,
  },
  {
    id: 'p9', name: 'Europe Highlights', destination: 'Europe', category: 'international',
    duration: '10 Days / 9 Nights', durationDays: 10, price: 129999, originalPrice: 165999,
    description: 'Grand European tour covering Paris, Swiss Alps, and Rome with iconic landmarks, scenic train rides, and cultural experiences.',
    highlights: ['Eiffel Tower visit', 'Swiss Alps Jungfraujoch', 'Gondola ride Venice', 'Colosseum Rome', 'Seine River Cruise'],
    inclusions: ['9 Nights 3-Star Hotels', 'Daily Breakfast', 'Eurostar/TGV Trains', 'All Sightseeing', 'Guided Tours', 'City Transfers'],
    exclusions: ['International Flights', 'Visa', 'Lunch & Dinner', 'Travel Insurance'],
    itinerary: [
      { day: 1, title: 'Arrival in Paris', description: 'Airport transfer. Evening Seine River cruise with city lights.' },
      { day: 2, title: 'Paris Sightseeing', description: 'Visit Eiffel Tower, Louvre Museum, Champs-Élysées, and Arc de Triomphe.' },
      { day: 3, title: 'Paris to Zurich', description: 'Train to Zurich. Afternoon city walk around Old Town and Lake Zurich.' },
      { day: 4, title: 'Jungfraujoch Day Trip', description: 'Scenic train to Top of Europe. Breathtaking Alpine views and snow activities.' },
      { day: 5, title: 'Interlaken', description: 'Adventure activities in Interlaken. Paragliding, lake cruise, or mountain hiking.' },
      { day: 6, title: 'Zurich to Venice', description: 'Train through scenic route. Arrive Venice. Evening St. Mark\'s Square walk.' },
      { day: 7, title: 'Venice Tour', description: 'Gondola ride, Doge\'s Palace, Rialto Bridge, and Murano glass island.' },
      { day: 8, title: 'Venice to Rome', description: 'High-speed train to Rome. Afternoon Trevi Fountain and Spanish Steps.' },
      { day: 9, title: 'Rome Sightseeing', description: 'Visit Colosseum, Roman Forum, Vatican City, and Sistine Chapel.' },
      { day: 10, title: 'Departure', description: 'Morning at leisure. Transfer to Rome airport for departure.' },
    ],
    image: 'https://images.unsplash.com/photo-1499856871958-5b9627545d1a?w=800', rating: 4.9, reviews: 156, maxGroupSize: 20,
  },
  {
    id: 'p10', name: 'Rishikesh Adventure Camp', destination: 'Rishikesh', category: 'adventure',
    duration: '4 Days / 3 Nights', durationDays: 4, price: 12999, originalPrice: 17999,
    description: 'Ultimate adventure getaway with white water rafting, bungee jumping, camping under stars, and yoga by the Ganges.',
    highlights: ['White water rafting (16km)', 'Bungee jumping (83m)', 'Cliff jumping', 'Beach camping', 'Morning yoga session'],
    inclusions: ['3 Nights Camp Stay', 'All Meals', 'Rafting (16km)', 'Camping Equipment', 'Bonfire & Music', 'Trained Instructors'],
    exclusions: ['Transport to Rishikesh', 'Bungee Jumping Fee', 'Personal Expenses', 'Insurance'],
    itinerary: [
      { day: 1, title: 'Arrival & Camp Setup', description: 'Arrive at Shivpuri camp. Beach activities, volleyball. Evening bonfire with music.' },
      { day: 2, title: 'Rafting Day', description: '16km white water rafting from Shivpuri to Laxman Jhula with cliff jumping stops.' },
      { day: 3, title: 'Adventure Activities', description: 'Bungee jumping, flying fox, and giant swing at Jumpin Heights. Evening Ganga Aarti.' },
      { day: 4, title: 'Yoga & Departure', description: 'Sunrise yoga session by the Ganges. Breakfast and departure.' },
    ],
    image: 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=800', rating: 4.7, reviews: 589, maxGroupSize: 30, difficulty: 'Moderate',
  },
  {
    id: 'p11', name: 'Ladakh Bike Expedition', destination: 'Ladakh', category: 'adventure',
    duration: '9 Days / 8 Nights', durationDays: 9, price: 35999, originalPrice: 44999,
    description: 'Epic motorcycle expedition through the highest motorable passes in the world, from Manali to Leh via Khardung La.',
    highlights: ['Ride Khardung La (18,380ft)', 'Pangong Lake visit', 'Nubra Valley camping', 'Magnetic Hill experience', 'Monastery visits'],
    inclusions: ['8 Nights Stay (Hotels + Camps)', 'All Meals', 'Royal Enfield Bike', 'Fuel', 'Mechanic Support', 'Oxygen Cylinders'],
    exclusions: ['Flights/Train to Manali', 'Riding Gear', 'Inner Line Permits', 'Medical Insurance'],
    itinerary: [
      { day: 1, title: 'Arrival in Manali', description: 'Arrive Manali. Bike allocation and briefing. Rest for acclimatization.' },
      { day: 2, title: 'Manali to Jispa', description: 'Ride through Rohtang Pass. Scenic route along Chandra River to Jispa.' },
      { day: 3, title: 'Jispa to Sarchu', description: 'Cross Baralacha La Pass. Stunning landscapes and remote terrain.' },
      { day: 4, title: 'Sarchu to Leh', description: 'Cross Lachalung La and Tanglang La. Arrive in Leh by evening.' },
      { day: 5, title: 'Leh Rest Day', description: 'Acclimatization day. Visit Leh Palace, Shanti Stupa, and local markets.' },
      { day: 6, title: 'Leh to Nubra Valley', description: 'Ride over Khardung La. Double humped camels at Hunder sand dunes.' },
      { day: 7, title: 'Nubra to Pangong', description: 'Ride to Pangong Lake via Shyok route. Camp at the iconic blue lake.' },
      { day: 8, title: 'Pangong to Leh', description: 'Morning at lake. Return to Leh via Chang La Pass. Farewell dinner.' },
      { day: 9, title: 'Departure', description: 'Bike return. Transfer to Leh airport for departure.' },
    ],
    image: 'https://images.unsplash.com/photo-1609766857326-18f208d6e8a8?w=800', rating: 4.9, reviews: 234, maxGroupSize: 10, difficulty: 'Challenging',
  },
  {
    id: 'p12', name: 'Jim Corbett Wildlife Safari', destination: 'Jim Corbett', category: 'adventure',
    duration: '4 Days / 3 Nights', durationDays: 4, price: 18999, originalPrice: 24999,
    description: 'Thrilling wildlife safari in India\'s oldest national park with tiger tracking, jeep safaris, and nature walks.',
    highlights: ['4 Jeep safaris', 'Tiger tracking', 'Bird watching tour', 'Corbett Museum visit', 'River crossing experience'],
    inclusions: ['3 Nights Jungle Resort', 'All Meals', '4 Jeep Safaris', 'Park Entry Fees', 'Naturalist Guide', 'Binoculars'],
    exclusions: ['Transport to Corbett', 'Camera Fees', 'Personal Expenses', 'Tips'],
    itinerary: [
      { day: 1, title: 'Arrival & First Safari', description: 'Arrive at Jim Corbett. Check into jungle resort. Afternoon jeep safari in Bijrani zone.' },
      { day: 2, title: 'Full Day Safaris', description: 'Early morning safari in Dhikala zone for tiger spotting. Afternoon safari in Jhirna zone.' },
      { day: 3, title: 'Safari & Nature Walk', description: 'Morning safari in Durga Devi zone. Afternoon guided nature walk and bird watching.' },
      { day: 4, title: 'Final Safari & Departure', description: 'Early morning safari. Breakfast. Visit Corbett Museum. Departure.' },
    ],
    image: 'https://images.unsplash.com/photo-1549366021-9f761d450615?w=800', rating: 4.6, reviews: 312, maxGroupSize: 8, difficulty: 'Easy',
  },
];
